---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  repository_dispatch:
    types: ['update']

concurrency:
  group: queue

jobs:
  workflows:
    name: Publish add-on update
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Run Repository Updater
        uses: hassio-addons/repository-updater@v1.2.5
        with:
          addon: ${{ github.event.client_payload.addon }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
